### ISSUE TITLE
Springracks Hosting

### ISSUE THREAD

**Issue by robocopnode** [setupmd/docs#101]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

Springracks Hosting

### Rule Violations

It's been 2 weeks already and they still haven't changed their policy. Was told to "make a new issue" if this policy wasn't changed. Either way, they can request a Summerhost Removal once they've fixed it.

Issue of https://github.com/setupmd/docs/issues/87

**Comment by ukdaaan** [comment]
bump @EternalTheGod

**Comment by EternalTheGod** [comment]
Will be added in the next PR.
