### ISSUE TITLE
Summerhost Addition - Pogohost

### ISSUE THREAD

**Issue by hoshic** [setupmd/docs#102]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

pogohost.com

### Rule Violations

There are no public terms of service, service-level agreement, or privacy policy.

**Comment by EternalTheGod** [comment]
The wiki is for Minecraft therefor I've stopped adding any hosts that do not offer Minecraft servers.
Pogohost does not seem to offer Minecraft hosting.
