### ISSUE TITLE
Suggestion- Sculk Host.

### ISSUE THREAD

**Issue by MrDadone** [setupmd/docs#105]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

Sculk host

### 1. No Service Level Agreement (SLA)
One of the major drawbacks of Sculk Host is the absence of a Service Level Agreement (SLA). An SLA is crucial for guaranteeing the reliability and performance of services, and its absence raises concerns about the commitment to service quality and uptime.

### 2. Misleading RAM Speed Claims
Sculk Host advertises RAM speeds of 6000MHz, which is misleading. Reliable hosting services typically offer RAM speeds around 3600MHz. This false claim can mislead customers about the performance they can expect.

![RAM Speed Claim](https://github.com/setupmd/docs/assets/154818659/e5664174-aecf-429a-a1f9-fc79691d3c75) 
![RAM Speed Comparison](https://github.com/setupmd/docs/assets/154818659/617b4162-1604-481c-a6cf-28de98835b91)

### 3. Undefined Storage Limits
Sculk Host does not specify the actual storage limits. This lack of transparency can lead to uncertainty and potential issues for users needing clear guidelines on storage capacity.

![Storage Limit](https://github.com/setupmd/docs/assets/154818659/f63741bc-b9c6-4deb-84c3-f6c4d3c82914)

### 4. Ambiguous Refund Policy
Sculk Host offers a 3-day money-back guarantee, but there is a contradictory clause that allows system admins to deem refund requests unacceptable. This ambiguity undermines the guarantee and can lead to customer dissatisfaction.

#### Terms of Service Excerpt:
> 5. Money Back Guarantee
> We offer a 3-day money-back guarantee. If you are not satisfied with our Services within the first 3 days of your subscription, you may request a full refund. Refund requests must be made within the 3-day period by contacting our support team.
> 
> "Refunds may be deemed unacceptable by system admins."

### 5. Excessive Direct Marketing
Sculk Host bombards other competitors with DM ad, and shit talks about the competitor to make his host look better

### 6. Recent Domain Registration
It's also worth noting that Sculk Host's domain was registered only at the start of this summer. This recent registration might raise concerns about the long-term reliability and stability of their services.

(Btw their removed from their uptime site the Panel and website uptime because it was always down) 
---

**Comment by EternalTheGod** [comment]
1 - Sculk has added an SLA policy to their Terms of Service
2 - Sculk has added an hardware page so that you know what each node would get: https://sculk.host/hardware
3 - The storage is unmetered, therefor does not have a hard limit
4 - This is normal as there are other hosts with such policies (ex. lilypad), and usually used if the refund policy is being abused
5 - I cannot approve this without any proof
6 - What's wrong with a new host having a newly registered domain?
