### ISSUE TITLE
Remove SpringRacks or else

### ISSUE THREAD

**Issue by michael1121q** [setupmd/docs#117]
### Declaration

- [X] I declare that I am authorised to speak on behalf of this business entity.
- [X] I declare that dishonestly completing this form will result in a permanent removal blacklist for the hosting entity.

### Hosting Provider Name

I demand the removal from SpringRacks now. I will sue you if you don't. You know nothing about the power we have.

### Evidence

If you don't like our rules, then leave. I recommend not crying on the internet you Turkish fool.

**Comment by smashyalts** [comment]
> ### Declaration
> 
>     * [x]  I declare that I am authorised to speak on behalf of this business entity.
> 
>     * [x]  I declare that dishonestly completing this form will result in a permanent removal blacklist for the hosting entity.
> 
> 
> ### Hosting Provider Name
> 
> I demand the removal from SpringRacks now. I will sue you if you don't. You know nothing about the power we have.
> ### Evidence
> 
> If you don't like our rules, then leave. I recommend not crying on the internet you Turkish fool.

"I demand the removal from SpringRacks now"
sorry but we here at setupmd cant help you give your letter of resignation, please go to your superiors at SpringRacks for that
