### ISSUE TITLE
(MADE BY ACTUAL STAFF OF SPRINGRACKS) Removal of SpringRacks Hosting from SummerHost List

### ISSUE THREAD

**Issue by TheVillainousBread** [setupmd/docs#126]
### Declaration

- [X] I declare that I am authorised to speak on behalf of this business entity.
- [X] I declare that dishonestly completing this form will result in a permanent removal blacklist for the hosting entity.

### Hosting Provider Name

SpringRacks Hosting

### Evidence

In the newest revision of our Terms of Services addresses the confusion made by the previous revision of the Terms of Service in the 31st of May 2023 Revision. This should be more clear on what we actually mean by the CPU usage. 

Here's the change for the offending items:
![image](https://github.com/user-attachments/assets/af1280a5-6c72-4170-bf6a-3e0110559644)

Here's the link for our Terms of Services:
https://my.springracks.com/plugin/support_manager/knowledgebase/view/8/terms-of-use/6/

Best regards,
Brandon
Support/Market Manager of SpringRacks

**Comment by EternalTheGod** [comment]
SpringRacks will be unlisted in the next PR.
