### ISSUE TITLE
UnknownHosting

### ISSUE THREAD

**Issue by Nufless** [setupmd/docs#132]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

Unknownhosting.net

### Rule Violations

No TOS or Privacy Policy
No SLA or Uptime Monitors
Lack of basic features (databases)

**Comment by EternalTheGod** [comment]
They do seem to have a Terms of Service and Privacy Policy at https://unknownhosting.net/terms-of-service/
We cannot force a host to offer additional resources, nor force them to add uptime monitoring. You can suggest this to them
I'll let them know regarding SLA.

Keep the issue open

**Comment by EternalTheGod** [comment]
They have a new terms of service which now covers SLA, though their privacy policy part is stripped.
I'll be listing them for the lack of a privacy policy
