### ISSUE TITLE
SliceNode

### ISSUE THREAD

**Issue by Nufless** [setupmd/docs#136]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

slicenode.xyz
billing.slicenode.xyz

### Rule Violations

- No TOS
- No Privacy Policy
- No SLA
- Runs off VPS
- Has a budget of $24
![image_2024-08-26_161200570](https://github.com/user-attachments/assets/7cfac514-207e-42c9-bd5e-0de1393ff5b7)
- No contact details

**Comment by EternalTheGod** [comment]
Will be added in the next PR.
