### ISSUE TITLE
VividMCC.com

### ISSUE THREAD

**Issue by Nufless** [setupmd/docs#139]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

VividMCC.com

### Rule Violations

- No TOS
- No Privacy Policy
- No SLA
- Discord checkout is available because their have no ddos protection and goes down multiple times a day
![image](https://github.com/user-attachments/assets/9ebba543-78c5-448b-a0be-2d933f8c3ec5)

**Comment by EternalTheGod** [comment]
They do seem to have a [Terms of Service](https://docs.google.com/document/d/10HgE8QJiEdOr0TfyuQmhZTTuJjx_UnyPdB5NMPDfCRc) link in their discord server (and apparently website, couldn't really confirm though). The Service Availability and Uptime section in their Terms of Service seem to be covering the SLA.
They will be listed for the lack of a Privacy Policy and improper checkout.
