### ISSUE TITLE
Switch from UnSignedVelocity to SignedVelocity

### ISSUE THREAD

**Issue by mallusrgreatv2** [setupmd/docs#147]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

In https://www.setup.md/t/signed-chat

Quoted from [GitHub](https://www.setup.md/t/signed-chat):
> UnSignedVelocity is a plugin that removes the limitation in Velocity to block or modify chat or commands executed by players with versions 1.19.1 or higher and who have a valid SignedKey. Although this works most of the time, there are issues that have arisen since version 1.19.3, which, as Mojang has implemented more security checks in the chat reporting system, has driven players kicked out of the proxy. SignedVelocity solves all these problems, synchronizing the blocking and modification of chat and commands to the backend server, where it is possible to modify the chat.

### Proposed solution (optional)

https://github.com/4drian3d/SignedVelocity

**Comment by ukdaaan** [comment]
After some consideration we're not going to address the change due to the EULA as no solutions are officially supported.
