### ISSUE TITLE
Flair Host

### ISSUE THREAD

**Issue by DominicTWHV** [setupmd/docs#149]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

Flair Host (https://flair.host/)

### Rule Violations

No public TOS/Privacy Policy on website

https://flair.host/terms-of-service
https://flair.host/privacy-policy
(or just broken links)

![image](https://github.com/user-attachments/assets/0ed41e13-753d-4e55-91e9-fa5057614bc5)
![image](https://github.com/user-attachments/assets/463e2a20-2a73-4bf4-9843-3c73dcf4db23)

**Comment by yfwemi** [comment]
https://flair.host/tos

**Comment by yfwemi** [comment]
https://flair.host/pp

**Comment by ukdaaan** [comment]
Report no longer valid
