### ISSUE TITLE
DHosting

### ISSUE THREAD

**Issue by domiehomie** [setupmd/docs#152]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

DHosting (https://host.diekieboy.com/)

### Rule Violations

At least no TOS, Privacy Policy, etc. Owner seems to be dutch (saw his message in helpchat dev requests) and also has no KVK number (requisition when owning a business) displayed on his website. Probably more to be found.

**Comment by EternalTheGod** [comment]
DHosting will be listed for the lack of a Terms of Service, Privacy Policy and SLA.
