### ISSUE TITLE
EnvyNodes

### ISSUE THREAD

**Issue by imlayered** [setupmd/docs#162]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

EnvyNodes(.xyz) 

### Rule Violations

* Improper checkout (Discord)
* No Terms of Service
* No Privacy Policy
* No SLA

**Comment by EternalTheGod** [comment]
They seem to have a Terms of Service and Privacy Policy now, but no SLA and they seem to be using discord checkout.
They will be listed for improper checkout and the lack of an SLA
