### ISSUE TITLE
Economy tab not in Server Enhancements front page menu and not capitalized

### ISSUE THREAD

**Issue by roxandtol** [setupmd/docs#33]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you sure this is not an issue in Docusaurus?

- [X] It is not a Docusaurus issue

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

title
![image](https://user-images.githubusercontent.com/41841903/194639856-2df087a1-74e0-4a34-bc54-15110ea76299.png)
![image](https://user-images.githubusercontent.com/41841903/194639910-108a4ce0-7292-435e-97f4-2e5ff3a3ee16.png)

**Comment by ukdaaan** [comment]
fixes implemented awaiting next merge before closing
