### ISSUE TITLE
Dead URL

### ISSUE THREAD

**Issue by Jcodeerd** [setupmd/docs#46]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you sure this is not an issue in Docusaurus?

- [X] It is not a Docusaurus issue

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

https://github.com/setupmd/docs/blob/d33572b474c6e34dfe3c87e6ba091bcde1da0cf4/guides/self-host/win.mdx?plain=1#L9
URL is dead

**Comment by ukdaaan** [comment]
URL has been adjusted thanks for the spot
