### ISSUE TITLE
Anti-X-ray page buttons not spaced out

### ISSUE THREAD

**Issue by mallusrgreatv2** [setupmd/docs#57]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you sure this is not an issue in Docusaurus?

- [X] It is not a Docusaurus issue

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

![image](https://github.com/setupmd/docs/assets/69511006/3c83fa14-cd7f-4515-9ef3-8504bf4fa59f)

**Comment by ukdaaan** [comment]
PR created to monitor status of Astro rewrite for topic #58
