### ISSUE TITLE
SOUR.HOST has officially removed FiveM

### ISSUE THREAD

**Issue by GTASwunk** [setupmd/docs#77]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you sure this is not an issue in Docusaurus?

- [X] It is not a Docusaurus issue

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

SOUR.HOST is listed under "Summer Hosts" on your setup.md page for selling preconfigured FiveM hosting. This has now been removed from the site, so I believe that we can be removed :D

**Comment by ukdaaan** [comment]
This has been removed based on the corrections being identified as completed.
