### ISSUE TITLE
NeptuneNode

### ISSUE THREAD

**Issue by Nufless** [setupmd/docs#79]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

Neptunenode
(neptunenode.com)

### Rule Violations

* Oversell servers by a large margin. They claim to have 192gb nodes, but it's actually only 128gb and they sell over 200gbs on each node. 
* For dedicated servers they resell Reliablesite
* About a month ago the owner, Anthony, leaked his login information to all his servers. Somebody then proceeded to delete everything. He then lied and claimed it to be a brute force, and said he would refund everyone. He refunded nobody. 
* Uses a pirated version of the theme for his website

**Comment by ukdaaan** [comment]
CC @EternalTheGod

**Comment by EternalTheGod** [comment]
This is missing evidence. Also there's nothing wrong with reselling (as long as you don't lie about this, which if you are there's probably a bigger lie behind it)
