### ISSUE TITLE
Summer Host Meteorite Host

### ISSUE THREAD

**Issue by Nufless** [setupmd/docs#80]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

meteoritehost
(meteoritehost.com)

### Rule Violations

* Sells through discord tickets
![image_2024-05-17_121333657](https://github.com/setupmd/docs/assets/169950939/641b9727-f92c-4a6e-a0ca-3954aa19b1ac)
* Founder is racist and says slurs 
![image_2024-05-17_121640105](https://github.com/setupmd/docs/assets/169950939/2ca114e6-cb87-4beb-a945-fe142c064ff5)
* Somebody ddosed them with a 1.5gb attack and it instantly crumpled, no ddos protection at all even though it is claimed on their website
* Oversell their servers
* Privacy Policy and Terms of Service are AI generated
* They plan on wiping all servers and ruining everything for their clients sometime in the future
![image_2024-05-17_122007670](https://github.com/setupmd/docs/assets/169950939/9928273a-eff7-41e3-a694-e92cf44ee397)

**Comment by ukdaaan** [comment]
CC @EternalTheGod

**Comment by ukdaaan** [comment]
Added, pending new commits

**Comment by EternalTheGod** [comment]
Meteorite has a billing page: https://billing.meteoritehost.com
Anything to back your "Heavy Overselling" claims? I doubt if this PR will live long if there's no additional context to back these claims.
