### ISSUE TITLE
Why exactly is my company on this website?

### ISSUE THREAD

**Issue by AnthonyCarafa** [setupmd/docs#82]
### Declaration

- [x] I declare that I am authorised to speak on behalf of this business entity.
- [X] I declare that dishonestly completing this form will result in a permanent removal blacklist for the hosting entity.

### Hosting Provider Name

NeptuneNode 
https://neptunenode.com

### Evidence

My servers aren't overallocted, I don't know what gave you that idea. There is a forged image going around saying 400,000MB/the Pterodactyl max but that just isn't correct. Screenshotted evidence is proved below. I don't overallocate. We're out of stock right now for a reason :D 

And how do I "null" my website theme? I didn't null any website theme... I paid for mine fair and square and it annoys me that is on here.

![chrome_kGdMktuqal](https://github.com/setupmd/docs/assets/124631913/41c31002-fc9f-4d04-b89c-4fd1dfec9a65)

**Comment by ignalred** [comment]
I keep mistyping stuff sorry for all of the edits lol

**Comment by ignalred** [comment]
Word came in the person who is posting it is also impersonating someone named Nukayy

**Comment by EternalTheGod** [comment]
Two issues were opened reporting Neptune Node, there is almost no evidence to back the claims (except for overallocation which cannot be proven and can be spoofed) so I'm probably going to remove Neptune with the next PR.
https://github.com/setupmd/docs/issues/81
https://github.com/setupmd/docs/issues/79
