### ISSUE TITLE
Add FurHost to summerhosts

### ISSUE THREAD

**Issue by michael1121q** [setupmd/docs#86]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

FurHost

### Rule Violations

You should add FurHost https://furhost.net/ to summerhosts right underneath Foxomy
FurHost is owned by Bun aka the same owner of Foxomy 
It’s obviously still active because he still pays for WHMCS on it
And their TOS page is blank, no SLA, no privacy policy

**Comment by ukdaaan** [comment]
@EternalTheGod

**Comment by ukdaaan** [comment]
Closing as not within Scope for the wiki. If this host decides to bring game services into their offerings then we will re-review our position.

**Comment by michael1121q** [comment]
They obviously do game services since they still **advertise** Minecraft hosting [here](https://furhost.net/index.php?rp=%2Fstore%2Fvps&language=english). Plus it’s also a **Managed VPS** which means they have to install a Minecraft server or whatever game server for you. It’s owned by the same owner of Foxomy too.
![image](https://github.com/setupmd/docs/assets/170896697/7cfa60ee-3895-45bc-b8b4-a3f4251981cf)
