### ISSUE TITLE
Springracks Hosting

### ISSUE THREAD

**Issue by robocopnode** [setupmd/docs#87]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

Springracks

### Matches this bullet point "Obstructive Terms of Service that disallows doing basic stuff within the server (ex. pregenning)"

From their TOS page https://my.springracks.com/plugin/support_manager/knowledgebase/view/8/terms-of-use/6/

`You are not allowed to run any task that will completely cap out the CPU limit set on your service.
Example:
If your server has a 200% CPU limit. You are not allowed to maintain 200% constantly for over a period of above 10 minutes. `
I guess pre gen world isn't allowed or having high spikes in players.

`You are not to abuse our Unlimited Storage by using Pre-Generation Mods or Plugins above 60GB of usage.`
Yup it's not allowed.

### Matches this bullet point "Website with false or missing information"

From their specs page https://my.springracks.com/plugin/support_manager/knowledgebase/view/22/node-specs/5/

Misleading/Inaccurate info on hardware specs.

`RAM: 192GB DDR4 @ 3200MHz`

AMD's AM5 supports DDR5, and DDR5 only and Reliablesite runs 192GB DDR5 at 3600 MHz max.

I also heard that Springracks may have relations with Lunes Hosting (another summerhost) since they assisted them in slandering other competitors. Not very professional nor surprising since they advertise very aggressively on Reddit and always compare themselves to other competitors.

https://i.imgur.com/J5xcurr.png

**Comment by ukdaaan** [comment]
@EternalTheGod

**Comment by EternalTheGod** [comment]
Looking into it

**Comment by EternalTheGod** [comment]
I've spoken to Brandon and their Terms of Service is apparently subject to a remake.
If these violations are still the case after that (or if they don't change their Terms of Service at all) feel free to make another issue.
