### ISSUE TITLE
Summerhost Addition - EmpireNodes

### ISSUE THREAD

**Issue by heyitslumi** [setupmd/docs#94]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

EmpireNodes

### Rule Violations

I have alot of summerhosts to report, but I wanna report a specific host due to them refusing to delete my account, even if the GDPR exists:

1. They do not have any proper information listed on their website or their TOS (https://dash.empirenodes.com/tos).
2. They do not have any privacy policy, and their TOS is actually a 1 to 1 replica to their Discord rules (https://dash.empirenodes.com/tos, they removed the privacy policy page). They also do not have any SLA.
3. I do not have any proof for this, as I am banned from their server for "alting and using a fake email", but they probably also do Discord checkout by selling their paid products.

After some days, my email I use to test the hosting was hacked, by sending spam e-mails, luckily I manage my own e-mails, and I highly suspect them to be the main culprit.

**Comment by heyitslumi** [comment]
I also have some image proofs if you guys want it.

**Comment by EternalTheGod** [comment]
The website is down so I'll be waiting until it's up in order to review. (Keep the issue open)

**Comment by heyitslumi** [comment]
I don't think their website is gonna be up soon since the website was down
when I argued with the owner.

Le mer. 12 juin 2024, 21:30, EternalTheGod ***@***.***> a
écrit :

**Comment by EternalTheGod** [comment]
Wouldn't be appropriate to list them when they don't have a website, though I'll perhaps wait a week and see if they do something about it.

**Comment by Nucceteere** [comment]
The website's some parts (https://dash.empirenodes.com/) are online. Their TOS is an exact copy of their Discord rules even with the emote names. They also strictly block Turkish IPs.

**Comment by ukdaaan** [comment]
bump @EternalTheGod

**Comment by EternalTheGod** [comment]
Will be added in the next PR.
