### ISSUE TITLE
Summerhosts addition - HostSpace.co.il

### ISSUE THREAD

**Issue by CerialPvP** [setupmd/docs#95]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

HostSpace, discord: https://discord.gg/CJsNuQ82, website: hostspace.co.il, going through a remake. The hosting provider is based on Israel, and their Discord server mainly speaks Hebrew, so I am translating all the provided content.

### Rule Violations

They violate the "Website with false or missing information" rule.
As I said earlier, their website is going through a remake, so their stuff's on Discord.
They have a "products" channel, with a dropdown to select products to view information about.
VPS (Regular):
![image](https://github.com/setupmd/docs/assets/71380797/ef271402-5164-4271-aaec-0caee14ecf74)
VPS (Gold):
![image](https://github.com/setupmd/docs/assets/71380797/6a1b1587-416b-4adb-9361-bf5159be8854)
Game server hosting:
![image](https://github.com/setupmd/docs/assets/71380797/90f47574-5107-4759-868a-e8756a54d91c)
![image](https://github.com/setupmd/docs/assets/71380797/a3fa39e9-f03c-44ed-a3af-64275d065e38)
Bot hosting:
![image](https://github.com/setupmd/docs/assets/71380797/2bc7cecb-5373-4c2a-b827-3c1a995a0269)
They also have a website hosting panel, but they said it's "coming soon".

In all those messages, there is no information about which CPU you're getting, and what RAM you're getting. In all messages (except game hosting, which doesn't say anything about tickets), they say that "you can open a ticket for further questions".
Thank you for reading this Eternal (and everyone else reading this)

**Comment by EternalTheGod** [comment]
sigh

**Comment by EternalTheGod** [comment]
Should be visible after the next PR has been merged
