### ISSUE TITLE
Add a new summerhost

### ISSUE THREAD

**Issue by GTASwunk** [setupmd/docs#96]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Hosting Provider Name

Cosmic Hosting (https://cosmichosting.xyz)

### Rule Violations

No publicly avaliable ToS, SLA, or Privacy Policy, Unauthorized FiveM GSP

**Comment by EternalTheGod** [comment]
Added - should be visible within the next PR
